bonus1:   audio/sfx/Powerup.ogg
bonus2:   audio/sfx/Powerup2.ogg
bonus3:   audio/sfx/Powerup3.ogg
bonus4:   audio/sfx/Powerup4.ogg
bonus5:   audio/sfx/Powerup5.ogg
bonus6:   audio/sfx/Powerup6.ogg
bonus7:   audio/sfx/Powerup7.ogg
bonus8:   audio/sfx/Powerup8.ogg
bonus9:   audio/sfx/Powerup9.ogg
bonus10:  audio/sfx/Powerup10.ogg
bonus11:  audio/sfx/Powerup11.ogg
bonus12:  audio/sfx/Powerup12.ogg
bonus13:  audio/sfx/Powerup13.ogg
bonus14:  audio/sfx/Powerup14.ogg
bonus15:  audio/sfx/Powerup15.ogg
bonus16:  audio/sfx/Powerup16.ogg
bonus17:  audio/sfx/Powerup17.ogg
bonus18:  audio/sfx/Powerup18.ogg
bonus19:  audio/sfx/Powerup19.ogg
bonus20:  audio/sfx/Powerup20.ogg
