package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/music/music-goes-here.txt", "assets/music/music-goes-here.txt");
			type.set ("assets/music/music-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/data/data-goes-here.txt", "assets/data/data-goes-here.txt");
			type.set ("assets/data/data-goes-here.txt", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup8.ogg", "assets/sounds/sfx/Powerup8.ogg");
			type.set ("assets/sounds/sfx/Powerup8.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup10.ogg", "assets/sounds/sfx/Powerup10.ogg");
			type.set ("assets/sounds/sfx/Powerup10.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup19.ogg", "assets/sounds/sfx/Powerup19.ogg");
			type.set ("assets/sounds/sfx/Powerup19.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup2.ogg", "assets/sounds/sfx/Powerup2.ogg");
			type.set ("assets/sounds/sfx/Powerup2.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup19.m4a", "assets/sounds/sfx/Powerup19.m4a");
			type.set ("assets/sounds/sfx/Powerup19.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup7.m4a", "assets/sounds/sfx/Powerup7.m4a");
			type.set ("assets/sounds/sfx/Powerup7.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup17.m4a", "assets/sounds/sfx/Powerup17.m4a");
			type.set ("assets/sounds/sfx/Powerup17.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup10.m4a", "assets/sounds/sfx/Powerup10.m4a");
			type.set ("assets/sounds/sfx/Powerup10.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup11.m4a", "assets/sounds/sfx/Powerup11.m4a");
			type.set ("assets/sounds/sfx/Powerup11.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup20.m4a", "assets/sounds/sfx/Powerup20.m4a");
			type.set ("assets/sounds/sfx/Powerup20.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup20.ogg", "assets/sounds/sfx/Powerup20.ogg");
			type.set ("assets/sounds/sfx/Powerup20.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup3.m4a", "assets/sounds/sfx/Powerup3.m4a");
			type.set ("assets/sounds/sfx/Powerup3.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup18.ogg", "assets/sounds/sfx/Powerup18.ogg");
			type.set ("assets/sounds/sfx/Powerup18.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup3.ogg", "assets/sounds/sfx/Powerup3.ogg");
			type.set ("assets/sounds/sfx/Powerup3.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup17.ogg", "assets/sounds/sfx/Powerup17.ogg");
			type.set ("assets/sounds/sfx/Powerup17.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup9.m4a", "assets/sounds/sfx/Powerup9.m4a");
			type.set ("assets/sounds/sfx/Powerup9.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup2.m4a", "assets/sounds/sfx/Powerup2.m4a");
			type.set ("assets/sounds/sfx/Powerup2.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup.m4a", "assets/sounds/sfx/Powerup.m4a");
			type.set ("assets/sounds/sfx/Powerup.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup4.ogg", "assets/sounds/sfx/Powerup4.ogg");
			type.set ("assets/sounds/sfx/Powerup4.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup14.ogg", "assets/sounds/sfx/Powerup14.ogg");
			type.set ("assets/sounds/sfx/Powerup14.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup18.m4a", "assets/sounds/sfx/Powerup18.m4a");
			type.set ("assets/sounds/sfx/Powerup18.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup7.ogg", "assets/sounds/sfx/Powerup7.ogg");
			type.set ("assets/sounds/sfx/Powerup7.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup8.m4a", "assets/sounds/sfx/Powerup8.m4a");
			type.set ("assets/sounds/sfx/Powerup8.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup14.m4a", "assets/sounds/sfx/Powerup14.m4a");
			type.set ("assets/sounds/sfx/Powerup14.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup13.ogg", "assets/sounds/sfx/Powerup13.ogg");
			type.set ("assets/sounds/sfx/Powerup13.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup.ogg", "assets/sounds/sfx/Powerup.ogg");
			type.set ("assets/sounds/sfx/Powerup.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup15.ogg", "assets/sounds/sfx/Powerup15.ogg");
			type.set ("assets/sounds/sfx/Powerup15.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup15.m4a", "assets/sounds/sfx/Powerup15.m4a");
			type.set ("assets/sounds/sfx/Powerup15.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup13.m4a", "assets/sounds/sfx/Powerup13.m4a");
			type.set ("assets/sounds/sfx/Powerup13.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup5.m4a", "assets/sounds/sfx/Powerup5.m4a");
			type.set ("assets/sounds/sfx/Powerup5.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup11.ogg", "assets/sounds/sfx/Powerup11.ogg");
			type.set ("assets/sounds/sfx/Powerup11.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup6.ogg", "assets/sounds/sfx/Powerup6.ogg");
			type.set ("assets/sounds/sfx/Powerup6.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup12.ogg", "assets/sounds/sfx/Powerup12.ogg");
			type.set ("assets/sounds/sfx/Powerup12.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup16.m4a", "assets/sounds/sfx/Powerup16.m4a");
			type.set ("assets/sounds/sfx/Powerup16.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup4.m4a", "assets/sounds/sfx/Powerup4.m4a");
			type.set ("assets/sounds/sfx/Powerup4.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup6.m4a", "assets/sounds/sfx/Powerup6.m4a");
			type.set ("assets/sounds/sfx/Powerup6.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup5.ogg", "assets/sounds/sfx/Powerup5.ogg");
			type.set ("assets/sounds/sfx/Powerup5.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup16.ogg", "assets/sounds/sfx/Powerup16.ogg");
			type.set ("assets/sounds/sfx/Powerup16.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup12.m4a", "assets/sounds/sfx/Powerup12.m4a");
			type.set ("assets/sounds/sfx/Powerup12.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("assets/sounds/sfx/Powerup9.ogg", "assets/sounds/sfx/Powerup9.ogg");
			type.set ("assets/sounds/sfx/Powerup9.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/images/button4.png", "assets/images/button4.png");
			type.set ("assets/images/button4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/slots.png", "assets/images/slots.png");
			type.set ("assets/images/slots.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/d16a.png", "assets/images/d16a.png");
			type.set ("assets/images/d16a.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/legend.png", "assets/images/legend.png");
			type.set ("assets/images/legend.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/bucky.png", "assets/images/bucky.png");
			type.set ("assets/images/bucky.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/star17 (copy).png", "assets/images/star17 (copy).png");
			type.set ("assets/images/star17 (copy).png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/button5.png", "assets/images/button5.png");
			type.set ("assets/images/button5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/button2.png", "assets/images/button2.png");
			type.set ("assets/images/button2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/legend_board.png", "assets/images/legend_board.png");
			type.set ("assets/images/legend_board.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/09-white.png", "assets/images/09-white.png");
			type.set ("assets/images/09-white.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/orientation.jpg", "assets/images/orientation.jpg");
			type.set ("assets/images/orientation.jpg", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/loading.png", "assets/images/loading.png");
			type.set ("assets/images/loading.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/gems.png", "assets/images/gems.png");
			type.set ("assets/images/gems.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/achievement.png", "assets/images/achievement.png");
			type.set ("assets/images/achievement.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/en_generic_rgb_wo_45.png", "assets/images/en_generic_rgb_wo_45.png");
			type.set ("assets/images/en_generic_rgb_wo_45.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/button.png", "assets/images/button.png");
			type.set ("assets/images/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/arrows/left.png", "assets/images/arrows/left.png");
			type.set ("assets/images/arrows/left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/arrows/right.png", "assets/images/arrows/right.png");
			type.set ("assets/images/arrows/right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/arrows/down.png", "assets/images/arrows/down.png");
			type.set ("assets/images/arrows/down.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/arrows/lrot.png", "assets/images/arrows/lrot.png");
			type.set ("assets/images/arrows/lrot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/arrows/rrot.png", "assets/images/arrows/rrot.png");
			type.set ("assets/images/arrows/rrot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/games_achievements.png", "assets/images/games_achievements.png");
			type.set ("assets/images/games_achievements.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/music_option.png", "assets/images/music_option.png");
			type.set ("assets/images/music_option.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/scores.png", "assets/images/scores.png");
			type.set ("assets/images/scores.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/sfx_option.png", "assets/images/sfx_option.png");
			type.set ("assets/images/sfx_option.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/games_controller.png", "assets/images/games_controller.png");
			type.set ("assets/images/games_controller.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/logo.png", "assets/images/logo.png");
			type.set ("assets/images/logo.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/09-red.png", "assets/images/09-red.png");
			type.set ("assets/images/09-red.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/star17.png", "assets/images/star17.png");
			type.set ("assets/images/star17.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/games_leaderboards.png", "assets/images/games_leaderboards.png");
			type.set ("assets/images/games_leaderboards.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/icon.png", "assets/images/icon.png");
			type.set ("assets/images/icon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/images/label.png", "assets/images/label.png");
			type.set ("assets/images/label.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/config/config.yaml", "assets/config/config.yaml");
			type.set ("assets/config/config.yaml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/fonts/OpenDyslexic-BoldItalic.ttf", "assets/fonts/OpenDyslexic-BoldItalic.ttf");
			type.set ("assets/fonts/OpenDyslexic-BoldItalic.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/OpenDyslexicAlta-Regular.ttf", "assets/fonts/OpenDyslexicAlta-Regular.ttf");
			type.set ("assets/fonts/OpenDyslexicAlta-Regular.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/OpenDyslexicAlta-Bold.ttf", "assets/fonts/OpenDyslexicAlta-Bold.ttf");
			type.set ("assets/fonts/OpenDyslexicAlta-Bold.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/OpenDyslexic-Regular.ttf", "assets/fonts/OpenDyslexic-Regular.ttf");
			type.set ("assets/fonts/OpenDyslexic-Regular.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/OpenDyslexic-Italic.ttf", "assets/fonts/OpenDyslexic-Italic.ttf");
			type.set ("assets/fonts/OpenDyslexic-Italic.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/OpenDyslexicMono-Regular.ttf", "assets/fonts/OpenDyslexicMono-Regular.ttf");
			type.set ("assets/fonts/OpenDyslexicMono-Regular.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/OpenDyslexicAlta-BoldItalic.ttf", "assets/fonts/OpenDyslexicAlta-BoldItalic.ttf");
			type.set ("assets/fonts/OpenDyslexicAlta-BoldItalic.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/OpenDyslexicAlta-Italic.ttf", "assets/fonts/OpenDyslexicAlta-Italic.ttf");
			type.set ("assets/fonts/OpenDyslexicAlta-Italic.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("assets/fonts/OpenDyslexic-Bold.ttf", "assets/fonts/OpenDyslexic-Bold.ttf");
			type.set ("assets/fonts/OpenDyslexic-Bold.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("fonts/OpenDyslexic-BoldItalic.ttf", "fonts/OpenDyslexic-BoldItalic.ttf");
			type.set ("fonts/OpenDyslexic-BoldItalic.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("fonts/OpenDyslexicAlta-Regular.ttf", "fonts/OpenDyslexicAlta-Regular.ttf");
			type.set ("fonts/OpenDyslexicAlta-Regular.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("fonts/OpenDyslexicAlta-Bold.ttf", "fonts/OpenDyslexicAlta-Bold.ttf");
			type.set ("fonts/OpenDyslexicAlta-Bold.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("fonts/OpenDyslexic-Regular.ttf", "fonts/OpenDyslexic-Regular.ttf");
			type.set ("fonts/OpenDyslexic-Regular.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("fonts/OpenDyslexic-Italic.ttf", "fonts/OpenDyslexic-Italic.ttf");
			type.set ("fonts/OpenDyslexic-Italic.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("fonts/OpenDyslexicMono-Regular.ttf", "fonts/OpenDyslexicMono-Regular.ttf");
			type.set ("fonts/OpenDyslexicMono-Regular.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("fonts/OpenDyslexicAlta-BoldItalic.ttf", "fonts/OpenDyslexicAlta-BoldItalic.ttf");
			type.set ("fonts/OpenDyslexicAlta-BoldItalic.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("fonts/OpenDyslexicAlta-Italic.ttf", "fonts/OpenDyslexicAlta-Italic.ttf");
			type.set ("fonts/OpenDyslexicAlta-Italic.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("fonts/OpenDyslexic-Bold.ttf", "fonts/OpenDyslexic-Bold.ttf");
			type.set ("fonts/OpenDyslexic-Bold.ttf", Reflect.field (AssetType, "font".toUpperCase ()));
			path.set ("images/button4.png", "images/button4.png");
			type.set ("images/button4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/slots.png", "images/slots.png");
			type.set ("images/slots.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/d16a.png", "images/d16a.png");
			type.set ("images/d16a.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/legend.png", "images/legend.png");
			type.set ("images/legend.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/bucky.png", "images/bucky.png");
			type.set ("images/bucky.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/star17 (copy).png", "images/star17 (copy).png");
			type.set ("images/star17 (copy).png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/button5.png", "images/button5.png");
			type.set ("images/button5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/button2.png", "images/button2.png");
			type.set ("images/button2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/legend_board.png", "images/legend_board.png");
			type.set ("images/legend_board.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/09-white.png", "images/09-white.png");
			type.set ("images/09-white.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/orientation.jpg", "images/orientation.jpg");
			type.set ("images/orientation.jpg", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/loading.png", "images/loading.png");
			type.set ("images/loading.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/gems.png", "images/gems.png");
			type.set ("images/gems.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/achievement.png", "images/achievement.png");
			type.set ("images/achievement.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/en_generic_rgb_wo_45.png", "images/en_generic_rgb_wo_45.png");
			type.set ("images/en_generic_rgb_wo_45.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/button.png", "images/button.png");
			type.set ("images/button.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/arrows/left.png", "images/arrows/left.png");
			type.set ("images/arrows/left.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/arrows/right.png", "images/arrows/right.png");
			type.set ("images/arrows/right.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/arrows/down.png", "images/arrows/down.png");
			type.set ("images/arrows/down.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/arrows/lrot.png", "images/arrows/lrot.png");
			type.set ("images/arrows/lrot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/arrows/rrot.png", "images/arrows/rrot.png");
			type.set ("images/arrows/rrot.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/games_achievements.png", "images/games_achievements.png");
			type.set ("images/games_achievements.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/music_option.png", "images/music_option.png");
			type.set ("images/music_option.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/scores.png", "images/scores.png");
			type.set ("images/scores.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/sfx_option.png", "images/sfx_option.png");
			type.set ("images/sfx_option.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/games_controller.png", "images/games_controller.png");
			type.set ("images/games_controller.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/logo.png", "images/logo.png");
			type.set ("images/logo.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/09-red.png", "images/09-red.png");
			type.set ("images/09-red.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/star17.png", "images/star17.png");
			type.set ("images/star17.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/games_leaderboards.png", "images/games_leaderboards.png");
			type.set ("images/games_leaderboards.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/icon.png", "images/icon.png");
			type.set ("images/icon.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("images/label.png", "images/label.png");
			type.set ("images/label.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("sfx/Powerup8.ogg", "sfx/Powerup8.ogg");
			type.set ("sfx/Powerup8.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup10.ogg", "sfx/Powerup10.ogg");
			type.set ("sfx/Powerup10.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup19.ogg", "sfx/Powerup19.ogg");
			type.set ("sfx/Powerup19.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup2.ogg", "sfx/Powerup2.ogg");
			type.set ("sfx/Powerup2.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup19.m4a", "sfx/Powerup19.m4a");
			type.set ("sfx/Powerup19.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup7.m4a", "sfx/Powerup7.m4a");
			type.set ("sfx/Powerup7.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup17.m4a", "sfx/Powerup17.m4a");
			type.set ("sfx/Powerup17.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup10.m4a", "sfx/Powerup10.m4a");
			type.set ("sfx/Powerup10.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup11.m4a", "sfx/Powerup11.m4a");
			type.set ("sfx/Powerup11.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup20.m4a", "sfx/Powerup20.m4a");
			type.set ("sfx/Powerup20.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup20.ogg", "sfx/Powerup20.ogg");
			type.set ("sfx/Powerup20.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup3.m4a", "sfx/Powerup3.m4a");
			type.set ("sfx/Powerup3.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup18.ogg", "sfx/Powerup18.ogg");
			type.set ("sfx/Powerup18.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup3.ogg", "sfx/Powerup3.ogg");
			type.set ("sfx/Powerup3.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup17.ogg", "sfx/Powerup17.ogg");
			type.set ("sfx/Powerup17.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup9.m4a", "sfx/Powerup9.m4a");
			type.set ("sfx/Powerup9.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup2.m4a", "sfx/Powerup2.m4a");
			type.set ("sfx/Powerup2.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup.m4a", "sfx/Powerup.m4a");
			type.set ("sfx/Powerup.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup4.ogg", "sfx/Powerup4.ogg");
			type.set ("sfx/Powerup4.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup14.ogg", "sfx/Powerup14.ogg");
			type.set ("sfx/Powerup14.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup18.m4a", "sfx/Powerup18.m4a");
			type.set ("sfx/Powerup18.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup7.ogg", "sfx/Powerup7.ogg");
			type.set ("sfx/Powerup7.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup8.m4a", "sfx/Powerup8.m4a");
			type.set ("sfx/Powerup8.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup14.m4a", "sfx/Powerup14.m4a");
			type.set ("sfx/Powerup14.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup13.ogg", "sfx/Powerup13.ogg");
			type.set ("sfx/Powerup13.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup.ogg", "sfx/Powerup.ogg");
			type.set ("sfx/Powerup.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup15.ogg", "sfx/Powerup15.ogg");
			type.set ("sfx/Powerup15.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup15.m4a", "sfx/Powerup15.m4a");
			type.set ("sfx/Powerup15.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup13.m4a", "sfx/Powerup13.m4a");
			type.set ("sfx/Powerup13.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup5.m4a", "sfx/Powerup5.m4a");
			type.set ("sfx/Powerup5.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup11.ogg", "sfx/Powerup11.ogg");
			type.set ("sfx/Powerup11.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup6.ogg", "sfx/Powerup6.ogg");
			type.set ("sfx/Powerup6.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup12.ogg", "sfx/Powerup12.ogg");
			type.set ("sfx/Powerup12.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup16.m4a", "sfx/Powerup16.m4a");
			type.set ("sfx/Powerup16.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup4.m4a", "sfx/Powerup4.m4a");
			type.set ("sfx/Powerup4.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup6.m4a", "sfx/Powerup6.m4a");
			type.set ("sfx/Powerup6.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup5.ogg", "sfx/Powerup5.ogg");
			type.set ("sfx/Powerup5.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup16.ogg", "sfx/Powerup16.ogg");
			type.set ("sfx/Powerup16.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("sfx/Powerup12.m4a", "sfx/Powerup12.m4a");
			type.set ("sfx/Powerup12.m4a", Reflect.field (AssetType, "binary".toUpperCase ()));
			path.set ("sfx/Powerup9.ogg", "sfx/Powerup9.ogg");
			type.set ("sfx/Powerup9.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("config/config.yaml", "config/config.yaml");
			type.set ("config/config.yaml", Reflect.field (AssetType, "text".toUpperCase ()));
			path.set ("assets/sounds/flixel.ogg", "assets/sounds/flixel.ogg");
			type.set ("assets/sounds/flixel.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/sounds/beep.ogg", "assets/sounds/beep.ogg");
			type.set ("assets/sounds/beep.ogg", Reflect.field (AssetType, "sound".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
